apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 80 # Le port du service
      targetPort: 8080 # Le port du pod où l'application écoute
